name: Merge-upstream-15

on:
  # 推送代码后触发
  push:
  # 定时任务触发，使用 cron 规则
  schedule:
    - cron: '*/15 * * * *'

jobs:
  fork_upstream:
    runs-on: ubuntu-latest
    steps:
      - run:
          echo "Current time is $(date +'%Y-%m-%d %H:%M:%S')"
      # 检出代码
      - name: CheckoutRepo
        uses: actions/checkout@v3
      # 同步  
      - name: GitHub Sync to Upstream Repository
        uses: rovast/sync-upstream-repo@v0.0.1
        with: 
          upstream_repo: https://github.com/LuckyJumpingFrog/TestForActions
          upstream_branch: main # change this
          downstream_branch: main # change this
          token: ${{ secrets.ACCESS_TOKEN }}
      # 检出代码
      - name: CheckoutRepo
        uses: actions/checkout@v3
      # 发送邮件
      - name: Send email
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp.sina.com
          account: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: zy
          from: ${{secrets.MAIL_USERNAME}}
          to: ${{secrets.MAIL_USERNAME}}
          subject: Merge-upstream-15 test ok.
          body: "this is a test for Merge-upstream-15"
          attachments: '[{"path":"README.md"}]'
